# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minbft_client_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bminbft_client_manager.proto\"\x13\n\x11GetClientNodesMsg\"\x1a\n\x18GetClientPublicRSAKeyMsg\"\x0b\n\tClientAck\"G\n\x17\x43lientServiceRequestMsg\x12\x15\n\roperationType\x18\x01 \x01(\x03\x12\x15\n\roperationData\x18\x02 \x01(\x03\"U\n\x12\x43onfigureClientMsg\x12\x16\n\x0e\x66\x61ultThreshold\x18\x01 \x01(\x03\x12\x15\n\rresendTimeout\x18\x02 \x01(\x03\x12\x10\n\x08\x63lientId\x18\x03 \x01(\x03\"\xb1\x01\n\x15\x43lientServiceReplyMsg\x12\x0e\n\x06nodeIp\x18\x01 \x01(\t\x12\x10\n\x08nodePort\x18\x02 \x01(\x03\x12\x16\n\x0esequenceNumber\x18\x03 \x01(\x03\x12\r\n\x05state\x18\x04 \x01(\x03\x12\x15\n\roperationType\x18\x05 \x01(\x03\x12\x15\n\roperationData\x18\x06 \x01(\x03\x12\x11\n\tsignature\x18\x07 \x01(\x0c\x12\x0e\n\x06nodeId\x18\x08 \x01(\x03\"Y\n\x0e\x43lientNodesDTO\x12\x0f\n\x07nodeIps\x18\x01 \x03(\t\x12\x11\n\tnodePorts\x18\x02 \x03(\x03\x12\x12\n\npublicKeys\x18\x03 \x03(\x0c\x12\x0f\n\x07nodeIds\x18\x04 \x03(\x03\"$\n\x15\x43lientPublicRSAKeyDTO\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x32\xe0\x02\n\x13MinbftClientManager\x12\x31\n\x08getNodes\x12\x12.GetClientNodesMsg\x1a\x0f.ClientNodesDTO\"\x00\x12.\n\x08setNodes\x12\x0f.ClientNodesDTO\x1a\x0f.ClientNodesDTO\"\x00\x12\x46\n\x0fgetPublicRSAKey\x12\x19.GetClientPublicRSAKeyMsg\x1a\x16.ClientPublicRSAKeyDTO\"\x00\x12\x38\n\x0eserviceRequest\x12\x18.ClientServiceRequestMsg\x1a\n.ClientAck\"\x00\x12\x34\n\x0cserviceReply\x12\x16.ClientServiceReplyMsg\x1a\n.ClientAck\"\x00\x12.\n\tconfigure\x12\x13.ConfigureClientMsg\x1a\n.ClientAck\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minbft_client_manager_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETCLIENTNODESMSG']._serialized_start=31
  _globals['_GETCLIENTNODESMSG']._serialized_end=50
  _globals['_GETCLIENTPUBLICRSAKEYMSG']._serialized_start=52
  _globals['_GETCLIENTPUBLICRSAKEYMSG']._serialized_end=78
  _globals['_CLIENTACK']._serialized_start=80
  _globals['_CLIENTACK']._serialized_end=91
  _globals['_CLIENTSERVICEREQUESTMSG']._serialized_start=93
  _globals['_CLIENTSERVICEREQUESTMSG']._serialized_end=164
  _globals['_CONFIGURECLIENTMSG']._serialized_start=166
  _globals['_CONFIGURECLIENTMSG']._serialized_end=251
  _globals['_CLIENTSERVICEREPLYMSG']._serialized_start=254
  _globals['_CLIENTSERVICEREPLYMSG']._serialized_end=431
  _globals['_CLIENTNODESDTO']._serialized_start=433
  _globals['_CLIENTNODESDTO']._serialized_end=522
  _globals['_CLIENTPUBLICRSAKEYDTO']._serialized_start=524
  _globals['_CLIENTPUBLICRSAKEYDTO']._serialized_end=560
  _globals['_MINBFTCLIENTMANAGER']._serialized_start=563
  _globals['_MINBFTCLIENTMANAGER']._serialized_end=915
# @@protoc_insertion_point(module_scope)
